[local]
localhost

[mongodb]
mongodb.srikanth865.online

[redis]
redis.srikanth865.online


[mysql]
mysql.srikanth865.online


[rabbitmq]
rabbitmq.srikanth865.online


[catalogue]
catalogue.srikanth865.online

[user]
user.srikanth865.online

[cart]
cart.srikanth865.online

[shipping]
shipping.srikanth865.online

[payment]
payment.srikanth865.online

[frontend]
frontend.srikanth865.online    