- name: python setup
  import_role:
    name: common 
    tasks_from: python


- name: creating systemuser
  import_role:
     name: common
     tasks_from: app-setup
- name: 

- name: copying service file and also deamon reloading
  import_role:
    name: common 
    tasks_from: systemd-setup

- name: enabling and restarted
  import_role:
    name: common
    tasks_from: restart